"""
Generate ieee_owen/config_tables.tex — the parameter and player-configuration tables.

Generated rather than hand-written on purpose. The two tables already in the manuscript
were transcribed by hand and the n=30 column drifted off its data (v^MIP, omega^LR and
both timings ended up carrying values from a single instance while the rest of the
column came from the 31-day sweep). A membership table is far easier to mistype than a
number table and far harder to catch, so the asset matrices below are read out of the
live CONFIGURATION_* objects and the shares are counted, never typed.

The scalar parameters ARE typed here, with the data_generator.py line they come from, on
the grounds that they are fixed constants of the market design rather than things that
move per experiment. Anything that varies across community size is derived.

Usage:  python ieee_owen/config_tables.py [-o ieee_owen/config_tables.tex]
"""
import os
import sys
import argparse

_PAPER = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_PAPER)
sys.path.insert(0, _PAPER)
sys.path.insert(0, _ROOT)
os.chdir(_ROOT)

import large_community as LC

# 6-prosumer configuration, mirroring run_multiday.C6 (the archetype set every larger
# community is built out of). Kept here rather than imported so that generating the
# tables does not drag in the solver stack.
CONFIGURATION_6 = {
    'players_with_wind': ['u1'], 'players_with_solar': [],
    'players_with_electrolyzers': ['u2'], 'players_with_heatpumps': ['u3'],
    'players_with_elec_storage': ['u1'], 'players_with_hydro_storage': ['u2'],
    'players_with_heat_storage': ['u3'],
    'players_with_nfl_elec_demand': ['u4'], 'players_with_nfl_hydro_demand': ['u5'],
    'players_with_nfl_heat_demand': ['u6'],
}
PLAYERS_6 = [f'u{i}' for i in range(1, 7)]

# (config key, column head, short tag used in the role strings)
ASSETS = [
    ('players_with_wind',             'Wind',        'W'),
    ('players_with_solar',            'Solar',       'S'),
    ('players_with_electrolyzers',    'ELZ',         'E'),
    ('players_with_heatpumps',        'HP',          'H'),
    ('players_with_elec_storage',     r'E-sto',      'e'),
    ('players_with_hydro_storage',    r'H$_2$-sto',  'h'),
    ('players_with_heat_storage',     r'Q-sto',      'q'),
    ('players_with_nfl_elec_demand',  r'$D^{E}$',    'de'),
    ('players_with_nfl_hydro_demand', r'$D^{H_2}$',  'dh'),
    ('players_with_nfl_heat_demand',  r'$D^{Q}$',    'dq'),
]
# Assets that put commitment binaries in a prosumer's subproblem. This is the split
# that matters for omega^LR: the Lagrangian gap is generated by these members alone.
BINARY_ASSETS = ('players_with_electrolyzers', 'players_with_heatpumps')

SIZES = [(6, PLAYERS_6, CONFIGURATION_6),
         (15, LC.PLAYERS_15, LC.CONFIGURATION_15),
         (30, LC.PLAYERS_30, LC.CONFIGURATION_30),
         (60, LC.PLAYERS_60, LC.CONFIGURATION_60)]


def has(cfg, key, p):
    return p in (cfg.get(key) or [])


def n_binary(cfg, players):
    """Members carrying at least one committed unit (union, not sum: u10-type members
    hold an electrolyser and could in principle hold a heat pump too)."""
    s = set()
    for k in BINARY_ASSETS:
        s |= set(cfg.get(k) or [])
    return len(s & set(players))


# --------------------------------------------------------------------------- tables
def tab_parameters():
    """Scalar parameters. Values from data_generator.py setup_lem_parameters()."""
    rows = [
        (r'\multicolumn{4}{@{}l}{\emph{Market and horizon}}', '', '', ''),
        (r'\quad Horizon $|T|$', '24', 'h', 'hourly resolution'),
        (r'\quad Carriers $|K|$', '3', '--', r'electricity, H$_2$, heat'),
        (r'\quad Coupling rows $m=(|K|+3)|T|$', '144', '--', 'fixed by the market design'),
        (r'\quad Households', '700', '--', 'demand scaling of the community'),
        (r'\quad Import/export price ratio', '1.5', '--', r'$\pi^{\mathrm{imp}}/\pi^{\mathrm{exp}}$'),
        (r'\quad H$_2$ reference price', '3.33', r'\euro/kg', '5000/1500'),
        (r'\quad Price data', r'\multicolumn{3}{l}{Jeju (KR) and DK2, January}', '', ''),
        (r'\midrule', '', '', ''),
        (r'\multicolumn{4}{@{}l}{\emph{Electrolyser (3-state commitment)}}', '', '', ''),
        (r'\quad Capacity $\overline{c}^{G}$', '1.0', 'MW', ''),
        (r'\quad Minimum load $c^{G}_{\min}$', '0.15', 'MW', r'$0.15\times$ capacity'),
        (r'\quad Standby draw $c^{G}_{\mathrm{sb}}$', '0.01', 'MW', ''),
        (r'\quad Start-up cost $c^{G}_{\mathrm{su}}$', '50', r'\euro', ''),
        (r'\quad Minimum down time', '2', 'h', ''),
        (r'\quad Efficiency curve', r'\multicolumn{3}{l}{piecewise linear, 6 segments}', '', ''),
        (r'\midrule', '', '', ''),
        (r'\multicolumn{4}{@{}l}{\emph{Heat pump (start-up/shut-down commitment)}}', '', '', ''),
        (r'\quad Capacity $\overline{c}^{H}$', '0.8', r'MW$_{\mathrm{th}}$', ''),
        (r'\quad Coefficient of performance $\nu^{\mathrm{cop}}$', '3.28', '--',
         'converts electric to heat'),
        (r'\quad Operating band $[c^{H}_{\min},c^{H}_{\max}]$', '[0.2, 0.8]', '--',
         'fraction of capacity'),
        (r'\quad Start-up cost $c^{H}_{\mathrm{su}}$', '10', r'\euro', ''),
        (r'\quad Ramp limits', '0.9', '--', 'up/down, start-up/shut-down'),
        (r'\midrule', '', '', ''),
        (r'\multicolumn{4}{@{}l}{\emph{Storage (per carrier $k$)}}', '', '', ''),
        (r'\quad Power rating', '0.25', '--', r'$\times$ the owner\'s asset capacity'),
        (r'\quad Energy capacity', '3.0', '--', r'$\times$ power rating'),
        (r'\quad Initial state of charge', '0.2', '--', 'fraction of energy capacity'),
        (r'\quad Round-trip efficiency, E / H$_2$', '0.95', '--', 'charge and discharge'),
        (r'\quad Round-trip efficiency, heat', '0.90', '--', 'charge and discharge'),
        (r'\midrule', '', '', ''),
        (r'\multicolumn{4}{@{}l}{\emph{Reserve and peak coupling}}', '', '', ''),
        (r'\quad Reserve price $\pi^{\mathrm{res}}$', '56', r'\euro/MW$\cdot$h',
         'Nordic FCR-N, DK2'),
        (r'\quad Reserve product', r'\multicolumn{3}{l}{symmetric, 4-hour blocks}', '', ''),
        (r'\quad Peak penalty $\delta^{\mathrm{peak}}$', '150', r'\euro/MW', ''),
    ]
    out = [r'% ---- generated by ieee_owen/config_tables.py ----',
           r'\begin{table}[!t]',
           r'\caption{Parameters of the community dispatch model. Held fixed across every '
           r'community size, so that the size axis varies $n$ alone.}',
           r'\label{tab:params}', r'\centering', r'\small',
           r'\begin{tabular}{@{}llll@{}}', r'\toprule',
           r'Parameter & Value & Unit & Note \\', r'\midrule']
    for r in rows:
        if r[0] == r'\midrule':
            out.append(r'\midrule')
        elif r[0].startswith(r'\multicolumn') or r'\multicolumn' in r[1]:
            out.append((r[0] if r[0].startswith(r'\multicolumn')
                        else f'{r[0]} & {r[1]}') + r' \\')
        else:
            out.append(f'{r[0]} & {r[1]} & {r[2]} & {r[3]} \\\\')
    out += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(out)


def tab_composition():
    """Asset counts and shares across the four community sizes."""
    out = [r'% ---- generated by ieee_owen/config_tables.py ----',
           r'\begin{table}[!t]',
           r'\caption{Composition of the four communities. Counts are members owning the '
           r'asset, shares in brackets. The $n=60$ community doubles every count at '
           r'$n=30$ exactly, so those two sizes differ in $n$ and in nothing else; the '
           r'smaller communities are not similar to them in every share, the asset mix '
           r'having been set by role rather than by proportion at $n=6$ and $n=15$. What '
           r'is held across all four is the last row -- the members carrying commitment '
           r'binaries, which are what generates $\omega^{\mathrm{LR}}$ -- so the '
           r'flatness of $\omega^{\mathrm{LR}}$ in $n$ is not confounded by a drifting '
           r'non-convex share.}',
           r'\label{tab:composition}', r'\centering', r'\small',
           r'\begin{tabular}{@{}l' + 'c' * len(SIZES) + r'@{}}', r'\toprule',
           ' & ' + ' & '.join(f'$n={n}$' for n, _, _ in SIZES) + r' \\', r'\midrule']
    for key, head, _ in ASSETS:
        cells = []
        for n, players, cfg in SIZES:
            c = len(set(cfg.get(key) or []) & set(players))
            cells.append(f'{c} ({100*c/n:.1f}\\%)' if c else '--')
        out.append(f'{head} & ' + ' & '.join(cells) + r' \\')
    out.append(r'\midrule')
    cells = []
    for n, players, cfg in SIZES:
        b = n_binary(cfg, players)
        cells.append(f'{b} ({100*b/n:.1f}\\%)')
    out.append(r'Members with commitment binaries & ' + ' & '.join(cells) + r' \\')
    out += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(out)


def tab_matrix(n, players, cfg, label, caption, mult=None):
    """Per-member asset matrix for one community size."""
    heads = ' & '.join(h for _, h, _ in ASSETS)
    ncol = len(ASSETS) + (2 if mult else 1)
    out = [r'% ---- generated by ieee_owen/config_tables.py ----',
           r'\begin{table}[!t]', f'\\caption{{{caption}}}', f'\\label{{{label}}}',
           r'\centering', r'\footnotesize',
           r'\setlength{\tabcolsep}{3pt}',
           r'\begin{tabular}{@{}l' + 'c' * (ncol - 1) + r'@{}}', r'\toprule',
           'Member & ' + heads + (r' & Cap.\ mult.' if mult else '') + r' \\',
           r'\midrule']
    for p in players:
        marks = [(r'$\bullet$' if has(cfg, k, p) else '') for k, _, _ in ASSETS]
        row = f'{p} & ' + ' & '.join(marks)
        if mult:
            m = mult.get(p)
            row += ' & ' + (', '.join(f'{k} {v}' for k, v in m.items()) if m else '1.0')
        out.append(row + r' \\')
    out += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--out', default=os.path.join(_PAPER, 'config_tables.tex'))
    args = ap.parse_args()

    parts = [
        '% =====================================================================',
        '% Parameter and player-configuration tables.',
        '% GENERATED by ieee_owen/config_tables.py -- edit that, not this file.',
        '% The asset matrices are read out of large_community.CONFIGURATION_* and the',
        '% shares are counted, so this file cannot drift away from what was solved.',
        '% Requires: booktabs, eurosym (\\euro).',
        '% =====================================================================',
        '',
        tab_parameters(),
        tab_composition(),
        tab_matrix(15, LC.PLAYERS_15, LC.CONFIGURATION_15, 'tab:config15',
                   'Member configuration of the 15-prosumer community. '
                   'u1--u6 are the 6-prosumer community unchanged.'),
        tab_matrix(30, [p for p in LC.PLAYERS_30 if int(p[1:]) > 15],
                   LC.CONFIGURATION_30, 'tab:config30',
                   'Members added at $n=30$. u1--u15 are Table~\\ref{tab:config15} '
                   'unchanged, so the 15-prosumer community is a sub-configuration of '
                   'this one.'),
        tab_matrix(60, [p for p in LC.PLAYERS_60 if int(p[1:]) > 30],
                   LC.CONFIGURATION_60, 'tab:config60',
                   'Members added at $n=60$. u1--u30 are unchanged. The last column is '
                   'the capacity multiplier applied to that member '
                   '(\\texttt{apply\\_60player\\_overrides}); every added member differs '
                   'from the archetype it mirrors, so the community is not a two-fold '
                   'replica of the 30-prosumer one -- a replica would shrink the core '
                   'toward the competitive allocation by Debreu--Scarf and the size '
                   'comparison would measure that instead.',
                   mult=LC._MULT_60),
    ]
    with open(args.out, 'w') as f:
        f.write('\n'.join(parts))
    print(f'wrote {args.out}')
    for n, players, cfg in SIZES:
        print(f'  n={n:2d}: {n_binary(cfg, players)} members with commitment binaries '
              f'({100*n_binary(cfg, players)/n:.1f}%)')


if __name__ == '__main__':
    main()
